export const PROJECT_TYPE_ALL = "ALL";
export const PROJECT_TYPE_API = "API";
export const PROJECT_TYPE_AI = "AI";
export const PROJECT_TYPE_CLI = "CLI";
export const PROJECT_TYPE_DESKTOP = "DESKTOP";
export const PROJECT_TYPE_DEVOPS = "DEVOPS";
export const PROJECT_TYPE_EXTENSION = "EXTENSION";
export const PROJECT_TYPE_WEB = "WEB";

export const PROJECT_FILTERS = [
  PROJECT_TYPE_ALL,
  PROJECT_TYPE_WEB,
  PROJECT_TYPE_AI,
  PROJECT_TYPE_DEVOPS,
  PROJECT_TYPE_API,
  PROJECT_TYPE_CLI,
  PROJECT_TYPE_EXTENSION,
  PROJECT_TYPE_DESKTOP,
];
